# Python文件编码报错

- `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 11: ordinal not in range(128)`

## 问题原因

- deepin 的默认编码是 'ascii'

```python
In [1]: import sys

In [2]: sys.getdefaultencoding()
Out[2]: 'ascii'
```

## 解决办法

- 重新设置文件编码

```python
In [4]: reload(sys)
<module 'sys' (built-in)>

In [5]: sys.setdefaultencoding('utf-8')

In [6]: sys.getdefaultencoding()
Out[6]: 'utf-8'
```